import { Inter } from "next/font/google";
import Navbar from "../components/navbar/Navbar";
import SessionWrapper from "@/components/sessionwrapper/sessionwrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <link rel="icon" href="/js_logo.png" />
        </head>
        <body className={`${inter.className} relative h-full overflow-y-auto`}>
          <SessionWrapper>
          <Navbar />
          <div className="fixed top-0 left-0 z-[-2] min-h-screen w-full bg-gray-900"></div>
          {children}
          </SessionWrapper>
        </body>
      </html>
    </>
  );
}
